import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import '@radix-ui/themes/styles.css';
import { Theme } from '@radix-ui/themes';
import { Toaster } from 'sonner';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body className={inter.className}>
          <Theme>
            <Header />
            <main className="min-h-screen bg-slate-700 px-12">
              {children}
            </main>
          </Theme>
          <Toaster position="top-center" richColors />
        </body>
    </html>
  );
}
